// Habillage du template de fiche v4 (04/09, cas Andy Yen) : tout le chrome
// rendu autour du contenu (titres de blocs, labels des triptyques, checklists,
// pool de questions, barre d'outils) existe en français ET en anglais. Une
// fiche dont identite.langue vaut "en" (épisode enregistré en anglais) se rend
// entièrement en anglais : le contenu anglais ne baigne plus dans un habillage
// français. Les bandeaux d'exploitation (gate anti fiche vide, génération en
// échec, erreurs d'envoi) restent en français : ils s'adressent à l'équipe,
// pas au lecteur de la fiche.

export type FicheLangue = "fr" | "en";

export const DEFAULT_CHECKLIST_EN = [
  "Airplane mode on both phones",
  "Notifications off, Slack closed",
  "Coffee and water on the table",
  "The cap",
  "Ceiling light off",
  "Sound check: two mics, two headsets",
  "Tell the guest: everything is recorded, we cut in the edit",
];

export const DEFAULT_CHECKLIST_POST_EN = [
  "Photos: guest alone, then with Matthieu",
  "Stop and check the audio and video files",
  "Send the rushes to the episode drive",
  "Voice memo to the team: what worked, what we cut",
  "Log the selected clips in the notebook",
  "Thank the guest and set the edit review date",
];

export const POOL_QUESTIONS_GENERALES_EN = [
  "Work the HOW harder: how? how? how?",
  "What we will talk about · Why I invited them · How we met · What's in it for me? · What do I expect from this episode?",
  "To start, I suggest you introduce yourself.",
  "What is your obsession right now? (follow up by repeating it with a question mark)",
  "How do you keep improving? · Where can people follow you, reach you?",
  "Whisper in your own ear · Worst sleepless night · Favourite failure · Most gifted book",
  "How do you organise your day-to-day?",
  "What is your mechanism? Do you have one? Do you hold a deep conviction?",
  "Your own north star",
  "What question would you ask yourself in an interview? What question should I ask you? What question would you rather I didn't ask?",
  "One part of your work life you would like to do better · Your big struggle right now",
  "What makes this episode a successful one?",
];

/** Chaînes de l'habillage, par langue. Les fonctions portent les libellés
 *  paramétrés (compteurs). */
export const CHROME_FICHE = {
  fr: {
    eyebrow: "Fiche de préparation",
    rec: "● REC",
    recOn: "■ En cours",
    preTitle: (n: number) => `Avant d'appuyer sur REC · ${n} gestes`,
    postTitle: (n: number) => `Avant de quitter le studio · ${n} gestes`,
    accompagnants: "ACCOMPAGNANTS",
    aConfirmer: "à confirmer",
    miseEnRelation: "MISE EN RELATION",
    photos: (nom: string) => `Photos · Google Images "${nom}" →`,
    catIntro: "Intro",
    catMarche: "Marché",
    catTopics: "Main topics",
    catApprofondissement: "Approfondissement",
    catSources: "Les sources",
    tldrSub: "Le briefing en 30 secondes",
    bioTimeline: "Bio timeline",
    bioTimelineSub: "Une ligne = une date = un fait · pro et perso mêlés",
    chiffres: "Les chiffres",
    chiffresSub: "Bloc propriétaire des valeurs · toute valeur est datée et sourcée",
    marcheTitre: "Où va l'argent du secteur",
    marcheSub: (n: number) => `Le contexte, en ${n} image${n > 1 ? "s" : ""}`,
    marcheParagraphe: "Le marché en un paragraphe",
    comparables: "Comparables",
    lexiqueTitre: (n: number) => `Lexique : les ${n} mots du métier, en une phrase chacun`,
    lexiqueSub: "Pour ne jamais être le seul du studio à ne pas comprendre",
    sujet: (n: number) => `Sujet ${n}`,
    contexte: "Le contexte",
    datesCles: "Dates clés",
    reflexions: "Réflexions",
    questions: "Questions",
    clickbaitSub: "Les questions qui piquent, et celles qui font apprendre · à doser selon la température du studio",
    clickbaitPiquantes: "Celles qui piquent (jusqu'à la gêne assumée)",
    clickbaitApprentissages: "Celles qui font apprendre (le meilleur de sa catégorie est en face de moi : qu'est-ce que je dois retenir ?)",
    clipsLegacySub: "Format v3.1 · régénérer la fiche pour le format clickbait",
    terrainConnu: "Terrain connu",
    terrainSub: "Ses réponses rodées, et la question de dépassement qui force du neuf",
    terrainQuestion: "La question qu'on lui pose partout",
    terrainReponse: "Sa réponse rodée",
    terrainDepassement: "Le dépassement",
    whosWho: "Who's who",
    whoQui: "Qui / rôle",
    whoEclaire: "Ce que ça éclaire",
    whoPreconfirmer: "À préconfirmer",
    apprentissages: "Les apprentissages",
    trypConnu: "Ce qu'on sait",
    trypManque: "Ce qui manque",
    trypQuestion: "La question",
    donneesCachees: "Données cachées",
    donneesCacheesSub: "Vieux dossiers et anecdotes introuvables dans les interviews récentes",
    zonesGrises: "Zones grises",
    zonesGrisesSub: "Ne jamais affirmer à l'antenne",
    aConsulter: "À consulter avant l'enregistrement",
    lectureTotale: (n: number) => `${n} min de lecture au total`,
    lecturesSub: "Les lectures indispensables et utiles",
    prioIndispensable: "Indispensable",
    prioUtile: "Utile",
    prioOptionnel: "Optionnel",
    deLecture: "de lecture",
    embargo: "Embargo",
    foldSources: (n: number) => `Toutes les sources consultées (${n})`,
    foldPool: "Questions générales de l'émission (pool fixe)",
    deplier: "+ Déplier",
    replier: "− Replier",
    legacyLabel: "Contenu d'un contrat antérieur (fiche non migrée)",
    ajouter: "Ajouter",
    nonLus: (n: number) => `${n} non lu(s)`,
    toolbar: {
      clips: { title: "Clips", hint: "questions à fort potentiel réseaux · challengées par l'équipe", ph: "Proposer un clip", empty: "Aucun clip validé. Les questions marquées CLIP dans les briques sont les candidates." },
      carnet: { title: "Carnet", hint: "notes prises en direct", ph: "Note en direct", empty: "Vide. À remplir pendant l'enregistrement." },
      regie: { title: "Régie", hint: "suivi technique et production", ph: "Entrée régie", empty: "Aucune entrée technique." },
    },
  },
  en: {
    eyebrow: "Prep sheet",
    rec: "● REC",
    recOn: "■ Recording",
    preTitle: (n: number) => `Before you hit REC · ${n} steps`,
    postTitle: (n: number) => `Before you leave the studio · ${n} steps`,
    accompagnants: "ACCOMPANIED BY",
    aConfirmer: "to be confirmed",
    miseEnRelation: "INTRODUCED BY",
    photos: (nom: string) => `Photos · Google Images "${nom}" →`,
    catIntro: "Intro",
    catMarche: "Market",
    catTopics: "Main topics",
    catApprofondissement: "Deep dive",
    catSources: "Sources",
    tldrSub: "The 30-second briefing",
    bioTimeline: "Bio timeline",
    bioTimelineSub: "One line = one date = one fact · pro and personal mixed",
    chiffres: "The numbers",
    chiffresSub: "The owner block for figures · every value is dated and sourced",
    marcheTitre: "Where the sector's money goes",
    marcheSub: (n: number) => `The context, in ${n} chart${n > 1 ? "s" : ""}`,
    marcheParagraphe: "The market in one paragraph",
    comparables: "Comparables",
    lexiqueTitre: (n: number) => `Lexicon: the ${n} words of the trade, one sentence each`,
    lexiqueSub: "So you are never the only one in the studio who does not get a word",
    sujet: (n: number) => `Topic ${n}`,
    contexte: "The context",
    datesCles: "Key dates",
    reflexions: "Insights",
    questions: "Questions",
    clickbaitSub: "The questions that sting, and the ones that teach · dose by studio temperature",
    clickbaitPiquantes: "The ones that sting (up to assumed awkwardness)",
    clickbaitApprentissages: "The ones that teach (the best in class is sitting across from me: what should I take away?)",
    clipsLegacySub: "v3.1 format · regenerate the sheet for the clickbait format",
    terrainConnu: "Familiar ground",
    terrainSub: "Their rehearsed answers, and the follow-up that forces something new",
    terrainQuestion: "The question they get everywhere",
    terrainReponse: "Their rehearsed answer",
    terrainDepassement: "The push beyond",
    whosWho: "Who's who",
    whoQui: "Who / role",
    whoEclaire: "What it sheds light on",
    whoPreconfirmer: "To pre-confirm",
    apprentissages: "The takeaways",
    trypConnu: "What we know",
    trypManque: "What's missing",
    trypQuestion: "The question",
    donneesCachees: "Hidden gems",
    donneesCacheesSub: "Old files and stories missing from recent interviews",
    zonesGrises: "Grey zones",
    zonesGrisesSub: "Never state on air",
    aConsulter: "To read before the recording",
    lectureTotale: (n: number) => `${n} min total reading`,
    lecturesSub: "The essential and useful reads",
    prioIndispensable: "Essential",
    prioUtile: "Useful",
    prioOptionnel: "Optional",
    deLecture: "read time",
    embargo: "Embargo",
    foldSources: (n: number) => `All sources consulted (${n})`,
    foldPool: "The show's standing questions (fixed pool)",
    deplier: "+ Expand",
    replier: "− Collapse",
    legacyLabel: "Content from an earlier contract (sheet not migrated)",
    ajouter: "Add",
    nonLus: (n: number) => `${n} unread`,
    toolbar: {
      clips: { title: "Clips", hint: "high-potential social questions · challenged by the team", ph: "Suggest a clip", empty: "No clip logged yet. The questions tagged CLIP in the topic cards are the candidates." },
      carnet: { title: "Notebook", hint: "live notes", ph: "Live note", empty: "Empty. To fill during the recording." },
      regie: { title: "Control room", hint: "tech and production channel", ph: "Control note", empty: "No entries yet." },
    },
  },
} as const;
